# Generated by Django 4.2.6 on 2023-11-30 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_alter_question_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='roll_no',
            new_name='uid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='set_attempted',
        ),
    ]
