# Generated by Django 4.2.6 on 2023-12-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_rename_roll_no_user_uid_remove_user_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unpromptedanswers',
            name='uid_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unpromptedanswers',
            name='user_id',
            field=models.CharField(max_length=200),
        ),
    ]
