# Generated by Django 4.2.6 on 2023-12-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_remove_unpromptedanswers_uid_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='unpromptedanswers',
            name='uid_no',
            field=models.IntegerField(default=0),
        ),
    ]
