# Generated by Django 4.2.6 on 2023-12-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='noassistanceanswers',
            name='uid_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='promptedanswers',
            name='uid_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='noassistanceanswers',
            name='user_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='promptedanswers',
            name='user_id',
            field=models.CharField(max_length=200),
        ),
    ]
