# Generated by Django 4.2.2 on 2024-01-31 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_auto_20240121_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noassistanceanswers',
            name='user',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='promptedanswers',
            name='user',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='unpromptedanswers',
            name='user',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
