# Generated by Django 4.2.2 on 2024-02-21 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0019_alter_noassistanceanswers_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noassistanceanswers',
            name='date',
            field=models.DateField(default='0001-01-01'),
        ),
        migrations.AddField(
            model_name='promptedanswers',
            name='date',
            field=models.DateField(default='0001-01-01'),
        ),
        migrations.AddField(
            model_name='unpromptedanswers',
            name='date',
            field=models.DateField(default='0001-01-01'),
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='cgpa',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='degree',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='uni',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
