# Generated by Django 4.2.2 on 2024-02-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0021_feedbackform_alter_noassistanceanswers_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackform',
            name='set',
            field=models.IntegerField(choices=[(1, 'Unprompted'), (2, 'Prompted'), (3, 'No Assistance')], null=True),
        ),
    ]
