# Generated by Django 4.2.2 on 2024-02-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_feedbackform_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackform',
            name='set',
            field=models.IntegerField(choices=[(1, 'Unprompted'), (2, 'Prompted'), (3, 'No Assistance')], default=1),
        ),
    ]
