# Generated by Django 4.2.2 on 2024-02-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0024_feedbackform_op1_feedbackform_op2_feedbackform_op3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackANS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200, null=True)),
                ('action', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('Start', 'Start'), ('End', 'End'), ('Continue', 'Continue')], default='Null', max_length=10)),
                ('set', models.IntegerField(choices=[(1, 'Unprompted'), (2, 'Prompted'), (3, 'No Assistance')], default=1)),
                ('time', models.TimeField(default='00:00:00')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
            ],
        ),
        migrations.RenameField(
            model_name='feedbackform',
            old_name='op1',
            new_name='option1',
        ),
        migrations.RenameField(
            model_name='feedbackform',
            old_name='op2',
            new_name='option2',
        ),
        migrations.RenameField(
            model_name='feedbackform',
            old_name='op3',
            new_name='option3',
        ),
        migrations.RenameField(
            model_name='feedbackform',
            old_name='op4',
            new_name='option4',
        ),
        migrations.RenameField(
            model_name='feedbackform',
            old_name='op5',
            new_name='option5',
        ),
        migrations.RenameField(
            model_name='feedbackform',
            old_name='question',
            new_name='questions',
        ),
        migrations.RemoveField(
            model_name='feedbackform',
            name='action',
        ),
        migrations.RemoveField(
            model_name='feedbackform',
            name='date',
        ),
        migrations.RemoveField(
            model_name='feedbackform',
            name='set',
        ),
        migrations.RemoveField(
            model_name='feedbackform',
            name='time',
        ),
        migrations.RemoveField(
            model_name='feedbackform',
            name='user',
        ),
    ]
