# Generated by Django 4.2.2 on 2024-02-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0025_feedbackans_rename_op1_feedbackform_option1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackans',
            name='page',
            field=models.CharField(default='Null', max_length=200),
        ),
    ]
